--
-- Generated by Raider.IO on 2026-07-29T08:04:58Z
-- All rights reserved.
--
local _, ns = ...

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 6738,
        ["instance_map_id"] = 1136,
        ["instance_map_ids"] = { 1136 },
        ["lfd_activity_ids"] = {  },
        ["name"] = "Siege of Orgrimmar",
        ["shortName"] = "SOO",
        ["localizationKey"] = "SOO",
    },
}
