--
-- Generated by Raider.IO on 2024-05-31T06:11:21Z
-- All rights reserved.
--
local _, ns = ...

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 4812,
        ["instance_map_id"] = 631,
        ["lfd_activity_ids"] = { 1110, 1111, 1255, 1264 },
        ["name"] = "Icecrown Citadel",
        ["shortName"] = "ICC",
    },
    [2] = {
        ["id"] = 4987,
        ["instance_map_id"] = 724,
        ["lfd_activity_ids"] = { 1108, 1109, 1256, 1265 },
        ["name"] = "The Ruby Sanctum",
        ["shortName"] = "RS",
    },
}
