--
-- Generated by Raider.IO on 2025-08-28T06:03:35Z
-- All rights reserved.
--
local _, ns = ...

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 6125,
        ["instance_map_id"] = 1008,
        ["lfd_activity_ids"] = { 335, 336, 337, 338 },
        ["name"] = "Mogu'shan Vaults",
        ["shortName"] = "MSV",
    },
}
